### ISSUE TITLE
Bugs(?)

### ISSUE THREAD

**Issue by KKKKKyle** [dd-center/DD_real_time_radar_frontend#3]
1. The missing link to 后端repo on the web. Does it get set to private for security issues?
2. Statistical graphs for word counts before 2019-09 are labeled as 1970-01. 

--Holo箱推，前来学习+DD+possible contribute(?)

**Comment by pren1** [comment]
Hello KKKKKyle,

> 1. The missing link to 后端repo on the web. Does it get set to private for security issues?

Well, the backend was private for some reason, and I think it has been open-sourced now.

> 2. Statistical graphs for word counts before 2019-09 are labeled as 1970-01.
> 

Part of the danmaku data collected does not have time information. So, those timestamps are set to 0. This problem should be fixed in the future :P

> --Holo箱推，前来学习+DD+possible contribute(?)

--这位同学，有兴趣加群吗？是使用github的vtuberDD程序员同好会dd-center的群～

**Comment by KKKKKyle** [comment]
噫好！我届到了！（

愿闻群号

(时区在美中 所以可能回复时间有点奇怪

**Comment by simon300000** [comment]
> 噫好！我届到了！（
> 
> 愿闻群号
> 
> (时区在美中 所以可能回复时间有点奇怪

663606562
欢迎哦→_→！
